name: "Check PR"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-public
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Installing dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13
      - name: Confirming everything is OK
        run: |
          ls -la venv

  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ install-dependencies ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13
      - name: Code Style
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          python -m pylint quality_control

  flake8-checks:
    name: Import style checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ install-dependencies ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.13
      - name: Flake8 check
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          python -m flake8 quality_control

  mypy-checks:
    name: Static types checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ install-dependencies ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup FIPL environment
        uses: fipl-hse/setup-env-action@v0.11
      - name: Flake8 check
        run: |
          source venv/bin/activate
          export PYTHONPATH=$(pwd)
          mypy quality_control
